Repository carefortheliving/frontend, pull requests merged in 2021-04, with the labels that each got.

#44 meta tag, favicon update
  public/about.txt
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: enhancement

#61 UI Improvements & Memory leakage fixes
  package.json
  public/index.html
  src/App.tsx
  src/components/common/Footer/View.tsx
  src/components/common/Navbar/View.tsx
  src/components/pages/CreateRequest/View.tsx
  src/components/pages/Dashboard/AddEditLinkCard.tsx
  src/components/pages/Dashboard/RequestFilters.tsx
  src/components/pages/Dashboard/View.tsx
  src/components/pages/SayThanks/View.tsx
  src/components/pages/ViewRequest/View.tsx
  src/hooks/useFirestore.ts
  src/hooks/useRoutes.ts
  src/index.css
  src/index.tsx
Labels: bug, enhancement

#69 Disqus homepage integration
  src/components/common/Disqus/View.tsx
  src/components/common/Navbar/View.tsx
  src/components/common/withAuth/View.tsx
  src/components/pages/CreateRequest/View.tsx
  src/components/pages/Dashboard/View.tsx
  src/components/pages/Login/View.tsx
  src/components/pages/ViewRequest/View.tsx
Labels: enhancement

#73 eslint-addition & optimization - 2
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/Constants/FilterData.tsx
  src/components/common/AppLoader/View.tsx
  src/components/common/AuthProvider/View.tsx
  src/components/common/Disqus/View.tsx
  src/components/common/Footer/View.tsx
  src/components/common/Navbar/FabIcon.tsx
  src/components/common/Navbar/View.tsx
  src/components/common/RouterOutlet/View.tsx
  src/components/common/ShareThis/index.tsx
  src/components/common/SnackbarProvider/View.tsx
  src/components/common/withAuth/View.tsx
  src/components/pages/About/View.tsx
  src/components/pages/CreateRequest/View.tsx
  src/components/pages/Dashboard/AddEditLinkCard.tsx
  src/components/pages/Dashboard/RequestFilters.tsx
  src/components/pages/Dashboard/View.tsx
  src/components/pages/Login/View.tsx
  src/components/pages/SayThanks/View.tsx
  src/components/pages/ViewRequest/View.tsx
  src/config.ts
  src/contexts/AppContext.tsx
  src/hooks/useFirebase.ts
  src/hooks/useFirestore.ts
  src/hooks/useGeo.tsx
  src/hooks/useRoutes.ts
  src/hooks/useUser.ts
  src/index.tsx
  src/react-app-env.d.ts
  src/resources/cities.json
  src/serviceWorker.ts
  src/types.ts
  src/utils/commonUtils.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#80 adding admin privilage, adding tab for closed req
  src/components/pages/Dashboard/View.tsx
  src/components/pages/ViewRequest/View.tsx
Labels: enhancement

#81 about, navbar ui enhance
  src/components/pages/About/View.tsx
  src/components/pages/Dashboard/View.tsx
Labels: enhancement

#84 firebase analytics added
  src/components/common/AuthProvider/View.tsx
  src/components/pages/About/View.tsx
  src/components/pages/CreateRequest/View.tsx
  src/components/pages/Dashboard/AddEditLinkCard.tsx
  src/components/pages/Dashboard/View.tsx
  src/components/pages/Login/View.tsx
  src/components/pages/SayThanks/View.tsx
  src/components/pages/ViewRequest/View.tsx
Labels: enhancement

#86 sort the request in descending order
  public/sw.js
  src/hooks/useFirestore.ts
Labels: bug
